### ISSUE TITLE
problems with certificate

### ISSUE THREAD

**Issue by fracanz** [uptake/uptasticsearch#206]
it looks like our certificate is not well recognized, and therefore I'd be able to always accept the certificate when I execute the call  <-es_search(es_host=.... 
I get:
Executing search request
Error in curl::curl_fetch_memory(url, handle = handle): server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Request failed [ERROR]

I should be able to add a "-k" as in a standard curl call (that's what works to my IT colleague)
Is there any way to add something like that to the call <-es_search(es_host=.... to accept always the certificate?
thank you very much for your help

**Comment by jameslamb** [comment]
Hi! Thanks for using `uptasticsearch`.

We need some additionoal information.

1. What `uptasticsearch`  version, R version, and operating system (including version) are you using?
2. What happens when you run this code in R, replacing `{ELASTICSEARCH}` with whatever you're passing to the `es_host` argument of `es_search()`

```r
httr::GET("{ELASTICSEACH}/_cat/indices?format=json")
```

To be clear, are you saying that you want the ability too trust this connection and ignore the certificate verification step? `-k` in `curl` is also called `--insecure` ([curl man page](https://curl.haxx.se/docs/manpage.html)) so be really sure you want to do that.

![image](https://user-images.githubusercontent.com/7608904/79674368-23015480-81a8-11ea-86a8-39fc85edaa2b.png)

`{uptasticsearch}` uses `{httr}` to make HTTP requests, which in turn uses `{curl}`. I believe you'll be able to solve your issue with something like [this solution](https://stackoverflow.com/a/37847994/3986677). 

```r
httr::set_config(
    httr::config(...)
)
resultDT <- uptasticsearch::es_search(...)
```

You can see all the valid options to be passed into the `httr::config()` part by this code:

```r
optionDF <- httr::httr_options()
```

The valid keyword arguments to pass to `httr::config()` are in the `httr` column of that dataframe. You can get the `curl` documentation for the corresponding `curl` option by running `httr::curl_docs()` and passing something  from the  `libcurl`  column. I see a bunch of options related to SSL there:

![image](https://user-images.githubusercontent.com/7608904/79674577-209ffa00-81aa-11ea-8a7a-fa1b7a715663.png)

Based on the contents of `httr::curl_docs("CURLOPT_SSL_VERIFYSTATUS")`, I would try this first:

```r
httr::set_config(
    httr::config(ssl_verifystatus = 0L)
)
resultDT <- uptasticsearch::es_search(...)
```

**Comment by austin3dickey** [comment]
For you or future viewers of this issue, I would also recommend determining whether you trust the certificate, and if so, telling your computer to trust it. [This SO question](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c) is about a Git server's certificate displaying the same problems (not Elasticsearch), but the process for doing so may be similar depending on your OS.

As James said, telling your computer to ignore untrusted certificates has some major potential security implications.

[This R curl vignette](https://cran.r-project.org/web/packages/curl/vignettes/windows.html) has a good discussion about using custom certificates if you're on Windows.

**Comment by fracanz** [comment]
thank you all, I have been able to perform the data import that I needed to do by following James's suggestions. We will change the certificate tomorrow, so it won't be needed again to use this not secure method. 
Thanks a lot again
Cheers

**Comment by jameslamb** [comment]
Awesome, glad it worked! Thanks for using `uptasticsearch`!
