### ISSUE TITLE
How to enter password and username in to the es_host

### ISSUE THREAD

**Issue by sebastiz** [uptake/uptasticsearch#218]
I am currently running uptasticsearch oand need to configure it connect to a remote server running elasticsearch.
There does not seem to be any way of adding a username and password which I suspect is the reason I get the following error. 

library(uptasticsearch)
commentDT <- es_search(
  es_host = 'https://*****:9200'
  , es_index = "customers"
  , query_body = qbody
  , scroll = "1m"
  , n_cores = 4
)

Error in curl::curl_fetch_memory(x$url$url, handle = x$url$handle) : 
  Failed to connect to ***** port 9200: Connection refused

Can you tell me how to enter these credentials?

Thanks

**Comment by jameslamb** [comment]
Hi @sebastiz , thanks for using `{uptasticsearch}`!

The error "connection refused" from `curl` isn't about authentication / authorization on the host you're trying to reach.

It's more likely that one of the following is happening:

1. Elasticsearch is running in a location that is not reachable from your current environment, due to firewall rules or other restrictions.
2. Elasticsearch is reachable but is not using port 9200 for its HTTP API. 9200 is the default port but it can be changed by administrators. It could also be different if Elasticsearch is being proxied by another service.
3. Elasticsearch is reachable but the cluster is currently not accepting new requests. This can happen during [a refresh](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html) or if the cluster was very recently started and it hasn't started up yet.

To diagnose this problem, you could try the following from the command line without involving `{uptasticsearch}` at all. Replace `YOUR_HOST` with the specific host name you are trying to hit.

```shell
curl -I https://YOUR_HOST:9200
```

If that works, you should see a message like this from Elasticsearch

```json
{
  "name" : "elasticsearch-0",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "EiVqzO1nQO6xivajv54Qyw",
  "version" : {
    "number" : "7.5.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "8bec50e1e0ad29dad5653712cf3bb580cd1afcdf",
    "build_date" : "2020-01-15T12:11:52.313576Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

You may need the help of an administrator on your Elasticsearch instance to figure out the correct value for `YOUR_HOST` and the correct port. If you can get that request working and `{uptasticsearch}` still reports an error, come back and we'll be happy to offer additional help.

**Comment by sebastiz** [comment]
Hi

Thanks so much for that useful responses it turns out it is a firewall issue.

Sebastian Zeki

On 16 Mar 2021, at 17:16, James Lamb ***@***.***> wrote:

﻿

Hi @sebastiz<https://github.com/sebastiz> , thanks for using {uptasticsearch}!

The error "connection refused" from curl isn't about authentication / authorization on the host you're trying to reach.

It's more likely that one of the following is happening:

  1.  Elasticsearch is running in a location that is not reachable from your current environment, due to firewall rules or other restrictions.
  2.  Elasticsearch is reachable but is not using port 9200 for its HTTP API. 9200 is the default port but it can be changed by administrators. It could also be different if Elasticsearch is being proxied by another service.
  3.  Elasticsearch is reachable but the cluster is currently not accepting new requests. This can happen during a refresh<https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html> or if the cluster was very recently started and it hasn't started up yet.

To diagnose this problem, you could try the following from the command line without involving {uptasticsearch} at all. Replace YOUR_HOST with the specific host name you are trying to hit.

curl -I https://YOUR_HOST:9200

If that works, you should see a message like this from Elasticsearch

{
  "name" : "elasticsearch-0",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "EiVqzO1nQO6xivajv54Qyw",
  "version" : {
    "number" : "7.5.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "8bec50e1e0ad29dad5653712cf3bb580cd1afcdf",
    "build_date" : "2020-01-15T12:11:52.313576Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

You may need the help of an administrator on your Elasticsearch instance to figure out the correct value for YOUR_HOST and the correct port. If you can get that request working and {uptasticsearch} still reports an error, come back and we'll be happy to offer additional help.

**Comment by jameslamb** [comment]
Ok, glad to hear you got it working! I'll close this issue then. Please come back and open a new issue if you run into any problems.
